### ISSUE TITLE
01-starting-setup.zip Not found

### ISSUE THREAD

**Issue by Blam030** [PacktPublishing/React---The-Complete-Guide-includes-Hooks-React-Router-and-Redux-Second-Edition#6]
Kia ora! 

I can only find reference to 01-starting-setup.zip in the readme and am not sure where to find it to download?

**Comment by Sonakshis** [comment]
Hi 
You can find the Section 1 resources under the section folder:
https://github.com/PacktPublishing/React---The-Complete-Guide-includes-Hooks-React-Router-and-Redux-Second-Edition/tree/main/Section%201%20Getting%20Started

We are in the process of updating the course by the end of this month.
