### ISSUE TITLE
Section 5, 11 and 13 have code.zip that is possibly corrupt

### ISSUE THREAD

**Issue by cwgabel** [PacktPublishing/React---The-Complete-Guide-includes-Hooks-React-Router-and-Redux-Second-Edition#7]
The code.zip may not be corrupt but I downloaded the entire repo as a zip and had no problem with the course until I hit section 5 where the code.zip is in an 'unsupported format' per my Mac utility attempting to open it.  Maybe this file was supposed to be expanded like the other sections.

**Comment by miahj1** [comment]
I'm on Mac, and it works fine for me. The third-party archive utilities on Mac OS tend to have some issues; however, they are far better than the default utility. The one I'm using is called [The Unarchiver](https://theunarchiver.com) which works successfully to extract that `code.zip` archive.

**Comment by cwgabel** [comment]
I didn't pursue that angle for I wondered why this particular lecture series (5) was structurally different than the prior ones. It does not have a 'code' subfolder as I suspect is inside of the zip file.  If nobody seems to think that the code.zip as it is doesn't need to be extracted like the others, I'll close this out.

**Comment by miahj1** [comment]
The structure for this repo is sloppy. 😔

**Comment by cwgabel** [comment]
I left the defaults stand asis on the The Unarchiver install but it failed to on both the entire repo unzipped code.zip file as well as an individual download of the code.zip file from  section 5.   Maybe Packt can get a new copy.

**Comment by cwgabel** [comment]
UPDATE:   The UnArchiver was successful on the standalone downloaded copy.

**Comment by cwgabel** [comment]
UPDATE:   The UnArchiver was successful on the standalone downloaded copy.
